### ISSUE TITLE
Help setup

### ISSUE THREAD

**Issue by surgiie** [Prefinem/MicroCF#1]
So this Micro Framework looks pretty cool. Im having some issues setting up i guess.

I followed your basic example and when i load the index.cfm, i simply get a blank page.

I have also noticed that when i run `cfpm add micro`

it only installs cfpm.cfc, cfpm.json and a empty vendor folder? So i actually had to manually download the files from this repo and place them in vendor.

im not sure why im getting a blank page though, i dump the application scope and

 application.cfpm is being set so im a bit confused.

**Comment by Raxvis** [comment]
Did you use the python cfpm or the new node cfpm?

Also, what webserver are you running?  micro was setup to run with nginx but apache should work.
(default nginx conf here: https://github.com/Prefinem/MicroCF/blob/master/nginx-basic.conf)

You will have to point everything to index.cfm.  If index.cfm is blank when you hit example.com/index.cfm, you probably need to add a route for it

```
micro.addRoute('GET', '/index.cfm', 'controllers.Index.home');
```

make sure you set cfpm correctly as well like this:

```
application.require = new cfpm();
```

If that is done, what do you get by dumping application.require('micro');

**Comment by surgiie** [comment]
Okay sorry i have found that that persisting variables to Application scope makes Coldfusion not respond to changes right away so that was the issue with loading the blank page but now i get:

I used new node cfpm and  Im running an apache server too. 

i have set `application.cfpm = new cfpm();` in application.cfc:

```
component 
{

     application.cfpm = new cfpm();
     writeDump(application.cfpm); //dumping this out to confirm it was set, which it is
}
```

then in index.cfm:

```
<cfscript>

micro = application.cfpm.require('micro',{baseDir: GetDirectoryFromPath(GetCurrentTemplatePath())});
micro.addRoute('GET', '/', 'controllers.Index.home');
micro.notFound('controllers.Index.fourOhFour');
micro.run();
return true;
</cfscript>

```

i do have a controllers directory with an index controller but now loading the page i get:

`Error loading Package: "micro" (vendor.micro.micro).`

I do have the micro.cfc in there so thats my issue now!

Any input would be helpful! Thanks!

**Comment by surgiie** [comment]
Error loading Package: "micro" (vendor.micro.micro). Invalid CFML construct found on line 61 at column 42.

Seems to be complaining about this line specifically in cfpm.cfc:
require function:

`this.packages[package] = new "#packageClass#"(params);`

**Comment by Raxvis** [comment]
What version of ColdFusion are you running?  Also, is it Lucee or Adobe?

**Comment by surgiie** [comment]
Adobe Coldfusion 11. There is talk of us upgrading to 2016 edition soon. Does this require 2016?

**Comment by Raxvis** [comment]
CF 11 should be fine.

Give me a little bit to test locally

**Comment by Raxvis** [comment]
Okay... found the issue.

You will need to download the new version of micro (version v0.0.2)

If you have git installed, you should be able to do

```
cfpm add micro
```

or if your cfpm.json is correct, then just cfpm should get you updated version

```
cfpm
```

or you can download the source

In short, micro was initially written for Lucee, there were a couple of issues with it as the syntax doesn't work on CF 11.  That should be fixed now.

On top of that, you will want to grab a new version of cfpm.cfc here: https://cfpm.io/install/cfc as it gives better errors now.

**Comment by Raxvis** [comment]
Any luck @surgiie ?

**Comment by surgiie** [comment]
Sorry, i meant to reply back. Yes i was able to get it loaded! :D Thanks for all your help!

**Comment by Raxvis** [comment]
Glad to hear it!  Closing the issue.  Let me know if you run into any other issues.

**Comment by surgiie** [comment]
Pretty cool package. I was inspired to write something as well by this:  Im somewhat new to this field and the CF architecture so my package uses the application scope for its components and essentially offers VC in MVC but is not as complex  microCF and does not feature middleware. As i mentioned during my time in college i was never taught what best practices/design patterns so honestly it is very mediocre and poorly designed and needs a lot of cleanups. Im looking for collaborators to help improve it. If you want to check it out: 

https://github.com/surgiie/CFSpark
